IntegratedBreedingPlatform/BMSAPI

src/test/java/org/ibp/api/brapi/v1/observation/ObservationResourceBrapiTest.java

IBP-2938 CreateTestForGetObservationlevels

---

src/main/java/org/ibp/api/java/impl/middleware/ontology/validator/FormulaValidator.java
src/test/java/org/ibp/api/java/impl/middleware/ontology/validator/FormulaValidatorTest.java
src/test/java/org/ibp/api/rest/ontology/FormulaResourceTest.java

IBP-2927 Limit cv id to variable when adding formula

---

src/main/java/org/ibp/api/rest/sample/SampleListResource.java

IBP-2950 Fix Sample List Search API in Swagger

---

src/main/java/org/ibp/api/java/impl/middleware/ontology/validator/FormulaValidator.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/ontology/validator/FormulaValidatorTest.java

IBP-1942 aggregate function sum implementation

---

src/main/java/org/ibp/api/java/impl/middleware/derived/DerivedVariableValidator.java

IBP-2965 -Check that the input variables are in subobs level on if the calculated variable is in plot data

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/AbstractDatasetExportService.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImplTest.java

IBP-2635 export csv improvements

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/AbstractDatasetExportService.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImpl.java

Changing HashMap for LinkedHashMap to preserve instances order

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGenerator.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGeneratorTest.java

IBP-3001 experimental design variables not exported

---

src/main/java/org/ibp/api/java/dataset/DatasetService.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImpl.java
src/main/java/org/ibp/api/rest/dataset/DatasetResource.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImplTest.java

Please merge. Related to https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/816

Add service get all variables for dataset

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/InventoryServiceImpl.java

Change if trndate from int to Date

---

src/main/java/org/ibp/api/rest/program/ProgramResource.java
src/test/java/org/ibp/api/rest/program/ProgramResourceTest.java

Restore api endpoint /program?cropName= 
IBP-3142-GetProgramByCropNameRestore

IBP-3142 Restore API Endpoint GetProgramByCropName

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVGenerator.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVGeneratorTest.java

IBP-3109 Categorical Variable Value Export Issue in CSV

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/InventoryServiceImpl.java

Change transaction status to COMMITED for every trx except Reservations

---

src/main/java/org/ibp/api/brapi/v1/study/StudyResourceBrapi.java
src/main/resources/brapi/calls.json
src/test/java/org/ibp/api/java/impl/middleware/call/CallServiceImplTest.java

cc @darla-leafnode @mcrimi @christineguiang @barbacenasmc

Hide not implemented api: brapi/v1/studies

---

src/test/java/org/ibp/api/java/impl/middleware/inventory/GermplasmValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/InventoryScaleValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LocationValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotInputValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/TransactionInputValidatorTest.java

Ibp 3279 lot tests

---

src/main/java/org/ibp/api/brapi/v1/germplasm/Germplasm.java
src/main/java/org/ibp/api/brapi/v1/germplasm/GermplasmResourceBrapi.java
src/main/java/org/ibp/api/brapi/v1/phenotype/PhenotypeSearchResource.java
src/main/java/org/ibp/api/brapi/v2/observation/ObservationUnitResourceBrapi.java

Move inner class to separate class

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVExportServiceImplTest.java

Remove fetch location, replace with StudyInstance Location property.

IBP-3048 Use Study Instance Location

---

src/main/java/org/ibp/api/brapi/v1/germplasm/GermplasmAttributes.java
src/main/java/org/ibp/api/brapi/v1/germplasm/GermplasmResourceBrapi.java
src/main/java/org/ibp/api/java/germplasm/GermplasmService.java
src/main/java/org/ibp/api/java/impl/middleware/common/validator/AttributeValidator.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmServiceImpl.java
src/main/resources/brapi/calls.json
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/call/CallServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/common/validator/AttributeValidatorTest.java

Ibp 3217 attributes brapi

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotInputValidator.java
src/main/resources/messages_en.properties

IBP-3174 fixing validate stockId prefix

---

src/main/java/org/ibp/api/brapi/v1/study/StudyResourceBrapi.java
src/main/java/org/ibp/api/brapi/v1/trial/TrialResourceBrapi.java
src/main/java/org/ibp/api/java/dataset/DatasetService.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImplTest.java

Transforms BRAPI observations format into dataset format to be imported by the same mechanism

IBP-3187 PUT /brapi​/v1​/studies​/{studyDbId}​/observations

---

src/main/java/org/ibp/api/brapi/v1/germplasm/GermplasmResourceBrapi.java
src/test/java/org/ibp/api/brapi/v1/germplasm/GermplasmResourceBrapiTest.java

Change get germplasm attributes endpoint remove the word 'search' from the end point.

IBP-3561-FixEndpoinGetGermplasmAttributes

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/TransactionServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotInputValidator.java
src/main/java/org/ibp/api/java/inventory/manager/LotService.java
src/main/java/org/ibp/api/rest/inventory/manager/LotResource.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotInputValidatorTest.java

https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/306
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/19
https://github.com/IntegratedBreedingPlatform/Middleware/pull/768

IBP-3515 update lots

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/TransactionServiceImpl.java
src/main/java/org/ibp/api/java/inventory/manager/TransactionService.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java

HI, @nahuel-soldevilla I made this PR in name of @clarysabel.
She created a new service to obtain the transaction involved available balance.
Include:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/20
https://github.com/IntegratedBreedingPlatform/Middleware/pull/770
Regards, Diego

IBP-3407 Query to get transactions that affects the available balance

---

src/main/java/org/ibp/api/java/impl/middleware/common/MiddlewareFactory.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/TransactionExportServiceImpl.java
src/main/java/org/ibp/api/java/inventory/manager/TransactionExportService.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/main/resources/messages_en.properties

Hi @nahuel-soldevilla and @clarysabel 
This is the new service to generate an excel file with the transactions recovered with the filter applied in the view Transactions in Inventory Manager
#Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/772
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/23
Please, review
Regards, Diego

IBP-3416 export transactions

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/TransactionInputValidator.java

Hi @clarysabel and @nahuel-soldevilla 
In this PR I added an extra validation to validate transactionIds parameter.
This solves the problem when trying to cancel pending transactions and Confirm pending transactions using the Search Request Id parameter.
Please, Review
Regards, Diego

IBP-3612 fixing Select all pages when cancel Pending transactions

---

src/main/java/org/ibp/api/security/WorkbenchUserDetailsService.java
src/test/java/org/ibp/api/security/WorkbenchUserDetailsServiceTest.java

IBP-3384 minimum security for brAPI calls

---

src/main/java/org/ibp/api/brapi/v1/security/auth/AuthenticationControllerBrapi.java

Token for BrAPI v2

---

src/test/java/org/ibp/ApiUnitTestBase.java
src/test/java/org/ibp/api/brapi/v2/observationunits/ObservationUnitResourceBrapiTest.java

Unit test for /{crop}/brapi​/v2​/search​/observationunits​/{searchResultDbId} to include previous versions properties

IBP-3679 Include Prior Versions Properties

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/common/validator/InventoryCommonValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotDepositRequestDtoValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotImportRequestDtoValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotInputValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotWithdrawalInputDtoValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/TransactionUpdateRequestDtoValidator.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotDepositRequestDtoValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotImportRequestDtoValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotInputValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotWithdrawalInputDtoValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/common/validator/InventoryCommonValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/TransactionUpdateRequestDtoValidatorTest.java

Using InventoryCommonValidator for notes length and units

---

src/test/java/org/ibp/api/java/impl/middleware/inventory/planting/validator/PlantingRequestDtoValidatorTest.java

Added PlantingRequestDtoValidatorTest

---

src/main/java/org/ibp/api/security/xauth/XAuthTokenFilter.java
src/test/java/org/ibp/api/security/xauth/XAuthTokenFilterTest.java

IBP-3422 Fix http error code of invalid crop or program UUID

---

src/main/java/org/ibp/api/rest/labelprinting/LabelPrintingResource.java
src/test/java/org/ibp/api/rest/labelprinting/LabelPrintingResourceTest.java

If user has Crop_Management role, allow to access label printing. 
Unit test for crop_management role and unauthorized

IBP-3814-CheckCropManagementRole

---

src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/test/java/org/ibp/api/rest/inventory/manager/TransactionResourceTest.java

Rename param to `{lotUUID}`
Fixes 2740de0949f7eb88835b4bd94db5b490c8128d26 (IBP-3760)

IBP-3871 Fix /lots/{lotId}/available-balance-transactions

---

src/main/java/org/ibp/api/java/impl/middleware/common/validator/GermplasmValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/common/SearchRequestDtoResolver.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotImportRequestDtoValidator.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/validator/LotInputValidator.java
src/main/java/org/ibp/api/java/inventory/manager/LotService.java
src/main/java/org/ibp/api/rest/inventory/manager/LotResource.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/inventory/GermplasmValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LotImportRequestDtoValidatorTest.java

- New service:
`POST /crops/{cropName}/lots/generation`
- Permissions
- Refactor gid validation

IBP-3750 germplasm manager - create inventory lots

---

src/main/java/org/ibp/api/java/impl/middleware/study/StudyServiceImpl.java
src/main/java/org/ibp/api/java/study/StudyService.java
src/main/java/org/ibp/api/rest/study/StudyResource.java

- Replicate Fieldbook StudyTreeController.getChildNodes into BMSAPI

IBP-3806 Inventory manager study filter: /studies/tree api

---

src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java

Hi @nahuel-soldevilla and @clarysabel 
In this PR I only modify the name of the permission.
Include:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/840
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/54
Please, review
Regards, Diego

IBP-3888 Replace permission by IMPORT_TRANSACTION_UPDATES.

---

src/main/java/org/ibp/api/domain/study/StudyInstance.java
src/test/java/org/ibp/api/rest/study/StudyInstanceResourceTest.java

Add experimentId value when creating new environment

IBP-3863-SetInstanceExperimentId

---

src/main/java/org/ibp/api/security/WorkbenchUserDetailsService.java
src/test/java/org/ibp/api/security/WorkbenchUserDetailsServiceTest.java

 IBP-3914 Added logic to skip crop checking if the user has Site Admin or parent permissions

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImplTest.java

IBP-3813-FixBrapiPostObservationUnits

---

src/main/java/org/ibp/api/rest/labelprinting/LabelPrintingStrategy.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationDatasetLabelPrinting.java
src/main/java/org/ibp/api/rest/labelprinting/SubObservationDatasetLabelPrinting.java
src/main/resources/messages_en.properties

Obtains all ObsUnitId grouped by a transaction.

IBP-3777 fixing get all ObsUnitId grouped by transaction

---

src/main/java/org/ibp/api/domain/common/LabelPrintingStaticField.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationDatasetLabelPrinting.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationLabelPrintingHelper.java
src/main/java/org/ibp/api/rest/labelprinting/SubObservationDatasetLabelPrinting.java
src/test/java/org/ibp/api/rest/labelprinting/ObservationDatasetLabelPrintingTest.java
src/test/java/org/ibp/api/rest/labelprinting/SubObservationDatasetLabelPrintingTest.java

IBP-3949 Refactor code label printing in Obs and SubObs.

---

src/main/java/org/ibp/api/rest/labelprinting/ObservationDatasetLabelPrinting.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationLabelPrintingHelper.java
src/main/java/org/ibp/api/rest/labelprinting/SubObservationDatasetLabelPrinting.java

IBP-4007 fields with alias names does not display the values on export labels

---

src/main/java/org/ibp/api/rest/dataset/DatasetResource.java
src/main/java/org/ibp/api/rest/derived/DerivedVariableResource.java
src/main/java/org/ibp/api/rest/design/CheckInsertionMannerResource.java
src/main/java/org/ibp/api/rest/design/ExperimentalDesignResource.java
src/main/java/org/ibp/api/rest/design/ExperimentalDesignTypeResource.java
src/main/java/org/ibp/api/rest/inventory/planting/PlantingResource.java
src/main/java/org/ibp/api/rest/inventory/study/StudyInventoryResource.java
src/main/java/org/ibp/api/rest/labelprinting/LabelPrintingResource.java
src/main/java/org/ibp/api/rest/ontology/VariableFilterResource.java
src/main/java/org/ibp/api/rest/preset/PresetResource.java
src/main/java/org/ibp/api/rest/sample/SampleListResource.java
src/main/java/org/ibp/api/rest/sample/SampleResource.java
src/main/java/org/ibp/api/rest/study/GermplasmStudySourceResource.java
src/main/java/org/ibp/api/rest/study/StudyGermplasmResource.java
src/main/java/org/ibp/api/rest/study/StudyInstanceResource.java
src/main/java/org/ibp/api/rest/study/StudyResource.java
src/main/java/org/ibp/api/rest/study/StudyTypeResource.java
src/main/java/org/ibp/api/rest/user/UserResource.java
src/main/java/org/ibp/controller/VariableCacheController.java
src/test/java/org/ibp/api/java/impl/middleware/UserTestDataGenerator.java

Include:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/919
https://github.com/IntegratedBreedingPlatform/Workbench/pull/372
https://github.com/IntegratedBreedingPlatform/Middleware/pull/887
Regard, Diego

IBP-3980 left side menu reorganization

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImpl.java
src/main/java/org/ibp/api/rest/dataset/ObservationsPutRequestInput.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetServiceImplTest.java

Added new logic to convert import file date value to follow yyMMdd if necessary 
Added new property in ObservationsPutRequestInput 
Unit test

IBP-2753-ImportKSUDateFormat

---

src/main/java/org/ibp/api/java/impl/middleware/design/util/ExperimentalDesignUtil.java
src/main/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImplTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/378
https://github.com/IntegratedBreedingPlatform/Middleware/pull/911
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/939
https://github.com/IntegratedBreedingPlatform/Commons/pull/284
Please, review
Regards, Diego

IBP-4058 Remove StockID variable from the ontology

---

src/main/java/org/ibp/api/java/breedingmethod/BreedingMethodService.java
src/main/java/org/ibp/api/java/germplasm/GermplasmService.java
src/main/java/org/ibp/api/java/impl/middleware/breedingmethod/BreedingMethodServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmServiceImpl.java
src/main/java/org/ibp/api/rest/breedingmethod/BreedingMethodResourceGroup.java
src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/breedingmethod/BreedingMethodServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmServiceImplTest.java

Ibp 4121 import germplasm services

---

src/main/java/org/ibp/api/Util.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVGenerator.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGenerator.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetCSVGeneratorTest.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGeneratorTest.java

Related to IBP-4010 
Check if variables map contains the name/alias of measurement variable 
Modified existing unit tests

IBP-4073-IBP-4123-CheckIfVariableNameExistsinVariableMap

---

src/main/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImplTest.java

If list has duplicate entry (gid), return previous germplasmlistdata

IBP-4131-DuplicateKeyInGermplasmListDataMap

---

src/main/java/org/ibp/api/security/xauth/UserXAuthTokenController.java

Deprecate Resource using instead "/token"
Include:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/388
Please, review
Regards, Diego

IBP-4043 Mark as Deprecated.

---

src/main/java/org/ibp/api/rest/sample/SampleListResource.java
src/main/java/org/ibp/api/rest/sample/SampleResource.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/393
https://github.com/IntegratedBreedingPlatform/Middleware/pull/933
Regards, Diego

IBP- 4151 Fixing SAMPLES LISTS permission

---

src/main/resources/brapi/calls.json

Hi @clarysabel - kindly merge.

IBP-3919 Register 2.0 support for GET /studies in calls.json

---

src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmExcelTemplateExportServiceImpl.java

IBP-4240 import germplasm update not include codes for storage location and units

---

src/main/java/org/ibp/api/java/impl/middleware/common/validator/LocationValidator.java

renamed location.uniqueID by location.programUUID

---

src/main/java/org/ibp/api/java/impl/middleware/common/MiddlewareFactory.java
src/main/java/org/ibp/api/java/impl/middleware/study/StudyServiceImpl.java
src/main/java/org/ibp/api/java/study/StudyService.java
src/test/java/org/ibp/api/java/impl/middleware/design/type/RandomizeCompleteBlockDesignTypeServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/study/StudyServiceImplTest.java

Delete DatabaseBroker
Cleanup StudyService

Removed DatabaseBroker.databaseName

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/AbstractDatasetExportService.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/BaseDatasetKsuExportService.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/TransactionExportServiceImpl.java
src/main/java/org/ibp/api/rest/dataset/DatasetResource.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/main/java/org/ibp/api/rest/labelprinting/LotLabelPrinting.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationDatasetLabelPrinting.java
src/main/java/org/ibp/api/rest/labelprinting/ObservationLabelPrintingHelper.java
src/main/java/org/ibp/api/rest/labelprinting/SubObservationDatasetLabelPrinting.java

Export study in excel, csv and ksu (csv/excel) 
Export inventory transactions 
Export label (Inventory)

IBP-4198-ExportFileName

---

src/main/java/org/ibp/api/brapi/v2/germplasm/BreedingMethod.java
src/main/java/org/ibp/api/brapi/v2/germplasm/BreedingMethodMapper.java
src/main/java/org/ibp/api/brapi/v2/germplasm/BreedingMethodResourceBrapi.java
src/main/java/org/ibp/api/java/breedingmethod/BreedingMethodService.java
src/main/java/org/ibp/api/java/impl/middleware/breedingmethod/BreedingMethodServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/common/validator/GermplasmUpdateDtoValidator.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmExcelTemplateExportServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/validator/GermplasmImportRequestDtoValidator.java
src/main/java/org/ibp/api/rest/breedingmethod/BreedingMethodResourceGroup.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/brapi/v2/germplasm/BreedingMethodResourceBrapiTest.java
src/test/java/org/ibp/api/java/impl/middleware/breedingmethod/BreedingMethodServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/common/validator/GermplasmUpdateDtoValidatorTest.java

Created new endpoints for /breedingmethods for brapi

IBP-4252-BrapiBreedingMethods

---

src/main/java/org/ibp/api/brapi/v2/germplasm/BreedingMethodResourceBrapi.java
src/test/java/org/ibp/api/brapi/v2/germplasm/BreedingMethodResourceBrapiTest.java

Change api endpoint to /{crop}/brapi/v2/breedingmethods/{breedingMethodDbId}

IBP-4252-AmendBrapiv2BreedingMethodById

---

src/main/resources/brapi/calls.json

New endpoints
breedingmethods
breedingmethods/{breedingMethodDbId}
germplasm
IBP-4244-IBP-4252-BrAPICall

IBP-4244-IBP-4252-BrAPICall

---

src/main/java/org/ibp/api/brapi/v1/program/ProgramResourceBrapi.java
src/main/java/org/ibp/api/brapi/v2/program/ProgramResourceBrapi.java
src/main/java/org/ibp/api/brapi/v2/validation/CropValidator.java
src/main/java/org/ibp/api/java/impl/middleware/program/ProgramServiceImpl.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/ApiUnitTestBase.java
src/test/java/org/ibp/api/brapi/v1/program/ProgramResourceBrapiTest.java
src/test/java/org/ibp/api/brapi/v2/program/ProgramResourceBrapiv2Test.java

- Do not return an error if there's no program found.
- Extract crop validation to a new class.
- Return HTTP Not Impemented error if abbreviation is specified.
IBP-4392

IBP-4392 Brapi Get Programs Improvements

---

src/main/java/org/ibp/api/java/germplasm/GermplasmService.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmServiceImpl.java
src/main/java/org/ibp/api/rest/germplasm/GermplasmAttributeResource.java
src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java

Implementing GET progenitor-details

---

src/main/java/org/ibp/api/domain/user/UserDetailDto.java
src/main/java/org/ibp/api/domain/user/UserMapper.java
src/main/java/org/ibp/api/java/impl/middleware/user/UserServiceImpl.java
src/main/java/org/ibp/api/java/user/UserService.java
src/main/java/org/ibp/api/rest/account/AccountResource.java

IBP-4449 make account resource return user detail dto instead user dto

---

src/main/java/org/ibp/api/rest/preset/PresetResource.java

IBP-4205 Adding missing permissions 

---

src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java

 IBP-4577 implement delete germplasm permission.

---

src/main/java/org/ibp/api/brapi/v1/study/StudyDetailsData.java
src/main/java/org/ibp/api/brapi/v2/location/LocationResourceBrapi.java
src/main/java/org/ibp/api/brapi/v2/study/StudyResourceBrapi.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/brapi/v1/location/LocationResourceBrapiTest.java

Fixing StudyDetailsDto to make it compliant with v2
Fixing v2 studies/id
IBP-4432

Implementing V2 Brapi locations/id

---

src/main/java/org/ibp/api/domain/user/UserProfileDto.java
src/main/java/org/ibp/api/domain/user/UserProfileUpdateRequestDTO.java
src/main/java/org/ibp/api/java/impl/middleware/manager/UserValidator.java
src/main/java/org/ibp/api/java/impl/middleware/user/UserServiceImpl.java
src/main/java/org/ibp/api/java/user/UserService.java
src/main/java/org/ibp/api/rest/user/profile/UserProfileResource.java
src/main/resources/messages_en.properties

IBP-4474 no change password when user logged in for the first time

---

src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java
src/main/java/org/ibp/api/rest/germplasmlist/GermplasmListResourceGroup.java
src/main/java/org/ibp/api/rest/keysequenceregister/KeySequenceResource.java

IBP-4572 verify correct imlementation of crop management permission

---

pom.xml
src/main/java/org/ibp/api/java/file/FileStorageService.java
src/main/java/org/ibp/api/java/impl/middleware/common/FileServiceFactory.java
src/main/java/org/ibp/api/java/impl/middleware/common/FileStorageServiceFactory.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/AbstractDatasetExportService.java
src/main/java/org/ibp/api/java/impl/middleware/file/AWSS3FileStorageServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/file/NoneFileStorageServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/file/SFTPFileStorageServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/ModelServiceImpl.java
src/main/java/org/ibp/api/rest/file/FileResource.java
src/main/resources/application.properties
src/test/java/org/ibp/api/java/impl/middleware/file/SFTPFileStorageServiceImplTest.java

- files api, post and get files
- aws (skd) and sftp (jsch, java secure channel library) implementations
- resolve configuration properties from env variables
- hide file datatype if not configured
- hide file columns from export

IBP-4568 file storage

---

src/main/java/org/ibp/api/security/SecurityConfiguration.java
src/main/java/org/ibp/api/security/oauth/OAuthController.java
src/main/resources/application.properties

* Add `baseUrl` property to set server public URL
* create endpoint `.well-known/openid-configuration`
Relates to https://github.com/PhenoApps/Field-Book/pull/208

IBP-4622: Basic KSU Field-book OpenId Connect setup

---

src/main/resources/application.properties

Moved prop to BMSConfig, removed unused property

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImpl.java
src/main/java/org/ibp/api/rest/common/PaginatedSearch.java
src/main/java/org/ibp/api/rest/study/GermplasmStudySourceResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImplTest.java

Please, review
Include:
IntegratedBreedingPlatform/Middleware#991
IntegratedBreedingPlatform/Workbench#434
IntegratedBreedingPlatform/Fieldbook#1018

IBP-4209 create inventory lot in search germplasm

---

src/main/java/org/ibp/api/java/impl/middleware/name/validator/GermplasmNameTypeValidator.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/name/GermplasmNameTypeValidatorTest.java

Added tests cases and messages error modified.
Please review.

IBP-4607 define new name types

---

src/main/java/org/ibp/api/domain/user/UserDetailDto.java

Removing annotation

---

src/main/java/org/ibp/api/rest/germplasmlist/GermplasmListResourceGroup.java

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/527

IBP-4840 Adding LISTS and GERMPLASM_LISTS permissions

---

src/main/java/org/ibp/api/rest/keysequenceregister/KeySequenceResource.java

IBP-4630 Added programUUID parameter to API endpoint

---

src/main/java/org/ibp/api/java/impl/middleware/manager/UserValidator.java
src/test/java/org/ibp/api/java/impl/middleware/manager/UserValidatorTest.java

Please revew.
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/532
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1112

IBP-4908 cannot use email grather than 40 characters

---

src/main/java/org/ibp/api/java/impl/middleware/name/GermplasmNameTypeService.java
src/main/java/org/ibp/api/java/impl/middleware/name/GermplasmNameTypeServiceImpl.java
src/main/java/org/ibp/api/rest/name/GermplasmNameTypeResource.java

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/540
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1126

IBP-4918 implement name types filter

---

src/main/java/org/ibp/api/rest/ontology/VariableResource.java

allow "manage germplasm" to:
- filter variables (germplasm details > descriptors > edit attributes > variable dropdown)
- list variable by id (germplasm details > descriptors > variable links)

IBP-4992: Include "MANAGE_GERMPLASM" permission in VariableResource

---

src/main/java/org/ibp/BmsApiFilter.java

Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/324

IBP-4810 missing header referrer policy

---

src/main/java/org/ibp/BmsApiFilter.java

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/323

IBP-4813 Setting X-Content-Type-Options into the response header.

---

src/main/java/org/ibp/api/java/impl/middleware/common/validator/LocationValidator.java
src/main/java/org/ibp/api/java/impl/middleware/program/ProgramServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/program/validator/ProgramFavoriteValidator.java
src/main/java/org/ibp/api/rest/program/ProgramFavoriteResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/program/favorite/ProgramFavoriteValidatorTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/565
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1147

IBP-5046 implement POST and DELETE program favorites Api

---

src/main/java/org/ibp/api/brapi/v1/phenotype/PhenotypeSearchResource.java

IBP-5169 Modified pagination

---

src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmListServiceImpl.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmListServiceImplTest.java

Creating on @mderamos'  behalf

IBP-5200 Added validation for ENTRY_NO values on import

---

src/main/java/org/ibp/api/java/impl/middleware/breedingmethod/BreedingMethodServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/common/validator/BreedingMethodValidator.java
src/main/java/org/ibp/api/java/impl/middleware/common/validator/LocationValidator.java
src/main/java/org/ibp/api/java/impl/middleware/location/LocationServiceImpl.java
src/main/java/org/ibp/api/rest/breedingmethod/BreedingMethodResourceGroup.java
src/main/java/org/ibp/api/rest/location/LocationResource.java
src/main/java/org/ibp/api/rest/name/GermplasmNameTypeResource.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/LocationValidatorTest.java

Hi, in this ticket also was included the new Locations and Breeding Methods Tabs.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1206
https://github.com/IntegratedBreedingPlatform/Workbench/pull/632

IBP-5335 Rename metadata to manage crop settings

---

src/main/java/org/ibp/api/domain/germplasmlist/GermplasmListMapper.java
src/main/java/org/ibp/api/java/germplasm/GermplasmListDataService.java
src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmListDataServiceImpl.java
src/main/java/org/ibp/api/rest/germplasmlist/GermplasmListResourceGroup.java
src/main/java/org/ibp/api/rest/labelprinting/GermplasmListLabelPrinting.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/rest/labelprinting/GermplasmListLabelPrintingTest.java

- new api to set generation level for a list and fill with cross expansion
- get cross from listdata in label printing

IBP-5369 fill with cross expansion

---

src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/inventory/manager/TransactionServiceImpl.java
src/main/java/org/ibp/api/rest/dataset/DatasetResource.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/inventory/TransactionServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/inventory/manager/LotServiceImplTest.java

Please, Review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1220
https://github.com/IntegratedBreedingPlatform/Workbench/pull/656
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1063

IBP-5394 create lots from planted observation units

---

src/main/java/org/ibp/api/java/impl/middleware/common/validator/LocationValidator.java

Fix comparison.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1230
https://github.com/IntegratedBreedingPlatform/Workbench/pull/665

IBP-4838 manage program settings beta

---

src/main/java/org/ibp/api/rest/labelprinting/LotLabelPrinting.java
src/test/java/org/ibp/api/rest/labelprinting/LotLabelPrintingTest.java

…0 characters if PDF file type
IBP-5579 / IBP-5422

IBP-5579-InventoryLabelPrintingAttributeValues

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/AbstractDatasetExportService.java

IBP-5585_remove_second_appearance_of_study_name_in_studybook_filename

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/BaseDatasetKsuExportService.java

IBP-5585 remove second appearance of study name in studybook filename

---

src/main/java/org/ibp/api/rest/dataset/DatasetResource.java
src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java
src/main/java/org/ibp/api/rest/germplasmlist/GermplasmListResource.java
src/main/java/org/ibp/api/rest/inventory/manager/LotResource.java
src/main/java/org/ibp/api/rest/inventory/manager/TransactionResource.java
src/main/java/org/ibp/api/rest/study/GermplasmStudySourceResource.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1081
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/102
https://github.com/IntegratedBreedingPlatform/Workbench/pull/705

IBP-4985_remove_single_entity_response

---

src/main/java/org/ibp/api/java/impl/middleware/common/MiddlewareFactory.java
src/main/java/org/ibp/api/java/impl/middleware/common/validator/CropNameValidationInterceptor.java
src/main/java/org/ibp/api/java/impl/middleware/crop/CropServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/ExperimentalDesignServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/manager/UserValidator.java
src/main/java/org/ibp/api/java/impl/middleware/study/StudyInstanceServiceImpl.java
src/test/java/org/ibp/ApiUnitTestBase.java
src/test/java/org/ibp/api/brapi/v1/program/ProgramResourceBrapiTest.java
src/test/java/org/ibp/api/brapi/v2/program/ProgramResourceBrapiv2Test.java
src/test/java/org/ibp/api/java/impl/middleware/common/validator/CropNameValidationInterceptorTest.java
src/test/java/org/ibp/api/java/impl/middleware/crop/CropServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/design/ExperimentalDesignServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/manager/UserValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/role/RoleServiceImplTest.java
src/test/java/org/ibp/api/java/impl/middleware/study/StudyInstanceServiceImplTest.java

IBP-5734 - IBP-5734-create-crop-service-in-middleware-to-move-workbench-data-manager-related-functions

---

src/main/java/org/ibp/api/java/impl/middleware/common/MiddlewareFactory.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/733
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1102
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1306

IBP-5774-Add_female_and_male_parents_columns_in_Germplasm_and_checks_tab

---

src/main/java/org/ibp/api/java/impl/middleware/ontology/OntologyMapper.java
src/main/java/org/ibp/api/rest/inventory/planting/PlantingResource.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1318
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1110

IBP-5450 Prepare planting using entry details variables

---

src/main/java/org/ibp/api/domain/ontology/Usage.java
src/main/java/org/ibp/api/domain/ontology/serializers/VariableDetailsSerializer.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/MethodServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/OntologyMapper.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/VariableServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/validator/MethodValidator.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/validator/TermDeletableValidator.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/validator/VariableValidator.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/ontology/validator/TermDeletableValidatorTest.java
src/test/java/org/ibp/api/rest/derived/DerivedVariableResourceTest.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/744
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1328

IBP-5835-ontology_method_for_sta_brapp

---

src/main/java/org/ibp/api/java/impl/middleware/study/validator/ObservationImportRequestValidator.java
src/test/java/org/ibp/api/rest/dataset/validator/ObservationImportRequestValidatorTest.java

Note: Pulled IBP-5824-AutomaticAssociationOfVariables to this branch

IBP-5596: fix observations to pending status on create from brapi

---

src/main/java/org/ibp/api/rest/file/FileResource.java

Fix authority checking

---

src/main/java/org/ibp/api/rest/labelprinting/GermplasmListLabelPrinting.java

IBP-5965-label_printing_of_germplasm_list_does_not_export_the_entry_no_values

---

src/main/java/org/ibp/api/java/impl/middleware/manager/UserValidator.java
src/main/resources/application.properties
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/UserTestDataGenerator.java
src/test/java/org/ibp/api/java/impl/middleware/manager/UserValidatorTest.java

IBP-5978-RestrictNumberOfActiveUsers

---

src/main/java/org/ibp/api/java/impl/middleware/design/type/AugmentedRandomizedBlockDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/type/EntryListOrderDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/type/PRepDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/type/RandomizeCompleteBlockDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/type/ResolvableIncompleteBlockDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/design/type/ResolvableRowColumnDesignTypeServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImpl.java
src/test/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGeneratorTest.java
src/test/java/org/ibp/api/java/impl/middleware/study/StudyEntryServiceImplTest.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1132
https://github.com/IntegratedBreedingPlatform/Commons/pull/367
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1375

IBP-4059 recategorize obs unit id as experimental design variable

---

src/main/java/org/ibp/api/brapi/v2/germplasm/PedigreeResourceBrapi.java

IBP-5981 Bring back pagination on pedigree search

---

src/main/java/org/ibp/api/brapi/v2/germplasm/PedigreeResourceBrapi.java

This reverts commit 9d4eed1afda34781dbd3ce6dffb4df8835760b9d.

IBP-5777 IBP-5981 Revert Addition Of Pagination In Pedigree Search

---

src/main/java/org/ibp/api/java/impl/middleware/common/MiddlewareFactory.java
src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetLock.java
src/main/java/org/ibp/api/rest/dataset/DatasetResource.java

Please, verify
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1144

IBP-5374 Duplicate rank when adding multiple traits to the study via import study book

---

src/main/java/org/ibp/api/domain/ontology/VariableDetails.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/OntologyMapper.java

IBP-6123-dataset_number_for_a_variable_appears_as_zero_in_ontology

---

src/main/java/org/ibp/api/rest/labelprinting/GermplasmListLabelPrinting.java
src/test/java/org/ibp/api/rest/labelprinting/GermplasmListLabelPrintingTest.java

IBP-6160-error_exporting_germplasm_list

---

src/main/java/org/ibp/api/java/impl/middleware/manager/UserValidator.java
src/main/java/org/ibp/api/java/impl/middleware/role/RoleServiceImpl.java
src/main/java/org/ibp/api/java/impl/middleware/user/UserServiceImpl.java
src/main/java/org/ibp/api/java/role/RoleService.java
src/main/java/org/ibp/api/java/user/UserService.java
src/main/java/org/ibp/api/rest/role/RoleResource.java
src/main/java/org/ibp/api/rest/user/UserResource.java
src/test/java/org/ibp/api/java/impl/middleware/manager/UserValidatorTest.java
src/test/java/org/ibp/api/java/impl/middleware/role/RoleServiceImplTest.java

Include:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1424
https://github.com/IntegratedBreedingPlatform/Workbench/pull/819

IBP-6185 build site admin with angular 7v

---

src/main/java/org/ibp/api/java/impl/middleware/study/validator/AdvanceValidator.java
src/main/resources/messages_en.properties
src/test/java/org/ibp/api/java/impl/middleware/study/validator/AdvanceValidatorTest.java

…e variable for breeding method selections in the observations

IBP-6189-as-a-user-i-want-to-advance-germplasm-from-sub-observations

---

src/main/java/org/ibp/api/java/impl/middleware/genotype/SampleGenotypeValidator.java
src/main/resources/messages_en.properties

IBP-6258 import genotype from file

---

src/main/java/org/ibp/api/brapi/v2/location/LocationMapper.java
src/main/java/org/ibp/api/brapi/v2/location/LocationResourceBrapi.java
src/main/java/org/ibp/api/brapi/v2/location/LocationSearchRequestDto.java

- separate location search request DTO for brapi v2

IBP-6283: fix filter of location on crop settings manager

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetExcelGenerator.java

IBP-6318_something_when_wrong_when_export_excel_study_book

---

src/main/java/org/ibp/api/java/impl/middleware/study/validator/AdvanceValidator.java
src/test/java/org/ibp/api/java/impl/middleware/study/validator/AdvanceValidatorTest.java

- check both nrep and rep_no are present before validation

IBP-6328/IBP-6329: fix advancing issue when rep_no is not present

---

src/main/java/org/ibp/api/rest/germplasm/GermplasmResource.java
src/test/java/org/ibp/api/rest/germplasm/GermplasmResourceTest.java

- change delete germplasm api to post: fixes the issue if too many germplasms are selected to be deleted

IBP-2856: allow deletion of more than 500 selected germplasm

---

src/main/java/org/ibp/api/java/impl/middleware/dataset/DatasetTransposedExcelGenerator.java

IBP-6364-FixIssueWhenExportingTransposedWithSingleNonFactorVariable

---

src/main/java/org/ibp/api/brapi/v2/observation/ObservationResourceBrapi.java

IBP-6375-FixGetObservationsBrapiError

---

src/main/java/org/ibp/api/domain/ontology/Usage.java
src/main/java/org/ibp/api/domain/ontology/serializers/VariableDetailsSerializer.java
src/main/java/org/ibp/api/java/impl/middleware/ontology/OntologyMapper.java

IBP-5758-IncludeLotsCountInVariableMetadata
